# Generated by Django 5.1.6 on 2025-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestayimage',
            name='image',
            field=models.ImageField(upload_to='homestays/'),
        ),
    ]
