# Generated by Django 5.1.6 on 2025-03-04 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0002_remove_homestay_host_id_homestay_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='district',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='district',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='province',
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homestays.province'),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='type',
            field=models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Căn hộ'), ('hotel', 'Khách sạn'), ('resort', 'Resort'), ('homestay', 'Homestay')], default='homestay', max_length=50),
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homestays.district')),
            ],
        ),
        migrations.AddField(
            model_name='homestay',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homestays.commune'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
