# Generated by Django 5.1.6 on 2025-03-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0002_alter_homestay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='homestays.district'),
        ),
    ]
