# Generated by Django 5.1.6 on 2025-03-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0003_alter_commune_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomestayAvailability',
        ),
    ]
