# Generated by Django 5.1.6 on 2025-03-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0003_remove_district_city_remove_homestay_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestay',
            name='images',
        ),
        migrations.CreateModel(
            name='HomestayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homestays/images')),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homestays.homestay')),
            ],
        ),
    ]
