# Generated by Django 5.1.6 on 2025-05-19 11:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0004_delete_homestayavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestayimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
