# Generated by Django 5.1.6 on 2025-05-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('host', 'Host'), ('guest', 'Guest'), ('admin', 'Admin')], default='guest', max_length=10),
        ),
    ]
